# Generated by Django 3.2.4 on 2021-07-29 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment_Done', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.FileField(blank=True, upload_to='resume/')),
                ('coverletter_text', models.CharField(max_length=250)),
                ('coverletter_link', models.FileField(blank=True, upload_to='cover_letter/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resume', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.IntegerField(null=True)),
                ('birth_month', models.IntegerField(null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married ', 'Married')], max_length=255, null=True)),
                ('profile_pic', models.ImageField(default='profile/avatar.png', upload_to='profile/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_profdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('start_date', models.IntegerField(null=True)),
                ('start_month', models.IntegerField(null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('end_date', models.IntegerField(null=True)),
                ('end_month', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profdetail', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_expdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('job_type', models.CharField(blank=True, choices=[('Part time', 'Part time'), ('Full time', 'Full time'), ('Internship', 'Internship')], max_length=255, null=True)),
                ('exp_salary', models.CharField(blank=True, max_length=150)),
                ('prefer_location', models.CharField(blank=True, max_length=150)),
                ('Total_Working', models.CharField(blank=True, max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expdetail', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=250)),
                ('start_date', models.IntegerField(null=True)),
                ('start_month', models.IntegerField(null=True)),
                ('start_year', models.IntegerField(null=True)),
                ('end_date', models.IntegerField(null=True)),
                ('end_month', models.IntegerField(null=True)),
                ('end_year', models.IntegerField(null=True)),
                ('course_type', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edu', to='jobseeker.candidate')),
            ],
        ),
    ]
