# Generated by Django 3.2.4 on 2021-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_order',
            name='resume_type',
            field=models.CharField(default='A', max_length=1024),
        ),
        migrations.AddField(
            model_name='resume_order',
            name='year_experience',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
