# Generated by Django 3.2.4 on 2021-06-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_candidate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
