# Generated by Django 3.2.4 on 2021-07-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_auto_20210729_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume_order',
        ),
    ]
