# Generated by Django 3.2.4 on 2021-06-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_auto_20210619_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate_Institute',
        ),
        migrations.RenameField(
            model_name='candidate_edu',
            old_name='institute_id',
            new_name='institute_name',
        ),
    ]
