# Generated by Django 3.2.4 on 2021-07-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_delete_resume_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment_Done', models.BooleanField(default=False)),
                ('year_experience', models.CharField(max_length=1024, null=True)),
                ('resume_type', models.CharField(default='A', max_length=1024)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
            ],
        ),
    ]
