# Generated by Django 3.2.4 on 2021-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_auto_20210627_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profdetail',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
