# Generated by Django 3.2.4 on 2021-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_auto_20210730_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_edu',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_edu',
            name='end_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_edu',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_edu',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_edu',
            name='start_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_edu',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
