# Generated by Django 3.2.4 on 2021-07-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_candidate_profdetail_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profile',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='candidate_profile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Candidate_expdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('job_type', models.CharField(blank=True, choices=[('Part time', 'Part time'), ('Full time', 'Full time'), ('Internship', 'Internship')], max_length=255, null=True)),
                ('exp_salary', models.CharField(blank=True, max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expdetail', to='jobseeker.candidate')),
            ],
        ),
    ]
