# Generated by Django 3.2.4 on 2021-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_auto_20210730_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_order',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
