# Generated by Django 3.2.4 on 2021-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_resume_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_order',
            name='amount',
            field=models.IntegerField(blank=True, default=250),
        ),
    ]
