# Generated by Django 3.2.4 on 2021-08-16 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_resume_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number. Correct format is 91XXXXXXXX', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
