# Generated by Django 3.2.4 on 2021-07-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_auto_20210716_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_expdetail',
            name='Total_Working',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate_expdetail',
            name='prefer_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
