# Generated by Django 3.2.4 on 2021-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_candidate_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_expdetail',
            name='Profile_Summary',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
