# Generated by Django 3.2.4 on 2021-07-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_auto_20210719_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_profile',
            name='profile_pic',
            field=models.ImageField(default='profile/avatar.png', upload_to='profile/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
