# Generated by Django 3.2.4 on 2021-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_alter_candidate_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_profile',
            name='profile_pic',
            field=models.ImageField(default='profile/avatar.png', upload_to='profile/'),
        ),
    ]
