# Generated by Django 3.2.4 on 2021-09-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0011_alter_candidate_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_order',
            name='resume_type',
        ),
        migrations.AddField(
            model_name='resume_order',
            name='delivery_type',
            field=models.CharField(default='Regular 8 working days', max_length=1024),
        ),
    ]
