# Generated by Django 3.2.4 on 2021-07-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0011_alter_candidate_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_resume',
            name='coverletter_link',
            field=models.FileField(blank=True, upload_to='cover_letter/'),
        ),
        migrations.AlterField(
            model_name='candidate_resume',
            name='resume_link',
            field=models.FileField(blank=True, upload_to='resume/'),
        ),
    ]
