# Generated by Django 3.2.4 on 2021-11-02 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0012_auto_20210926_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number. Correct format is 91XXXXXXXX', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
