# Generated by Django 3.2.4 on 2021-11-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0013_alter_candidate_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_resume',
            name='coverletter_link',
        ),
        migrations.RemoveField(
            model_name='candidate_resume',
            name='coverletter_text',
        ),
    ]
