# Generated by Django 3.2.4 on 2021-11-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0014_auto_20211113_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_expdetail',
            name='Profile_Summary',
        ),
        migrations.CreateModel(
            name='Resume_headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_headline', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_headline', to='jobseeker.candidate')),
            ],
        ),
    ]
