# Generated by Django 3.2.4 on 2021-11-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0016_auto_20211116_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profile',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate_profile',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
