# Generated by Django 3.2.4 on 2021-06-18 13:50

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('company_type', models.CharField(blank=True, max_length=250)),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_jobs',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=1250)),
                ('job_description', models.CharField(max_length=1250)),
                ('employment_type', models.CharField(max_length=250)),
                ('job_location', models.CharField(max_length=250)),
                ('job_experience', models.CharField(max_length=250)),
                ('job_savelater', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_jobquestions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1250)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_job_responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_expired_jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_candidate_jobanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1250)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobs')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobquestions')),
            ],
        ),
    ]
