# Generated by Django 3.2.4 on 2021-09-06 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0010_candidate_expdetail_profile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1250)),
                ('employment_type', models.CharField(blank=True, choices=[('Part time', 'Part time'), ('Full time', 'Full time'), ('Internship', 'Internship')], max_length=25, null=True)),
                ('skill', models.CharField(max_length=100, null=True)),
                ('job_location', models.CharField(max_length=50)),
                ('job_experience', models.CharField(max_length=20)),
                ('is_save_later', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number. Correct format is 91XXXXXXXX', regex='^\\+?1?\\d{9,15}$')])),
                ('company_type', models.CharField(blank=True, max_length=250)),
                ('company_name', models.CharField(blank=True, max_length=250)),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_jobquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer_size', models.IntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_job_Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_job_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_on', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_job_Applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_expired_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_candidate_jobanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1250)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.candidate')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobquestion')),
            ],
        ),
    ]
