# Generated by Django 3.2.4 on 2021-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_jobquestion',
            name='answer_size',
        ),
    ]
