# Generated by Django 3.2.4 on 2021-06-19 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number. Correct format is 04XXXXXXXX', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
