# Generated by Django 3.2.4 on 2021-06-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_employer_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1250)),
                ('job_description', models.CharField(max_length=1250)),
                ('employment_type', models.CharField(max_length=250)),
                ('job_location', models.CharField(max_length=250)),
                ('job_experience', models.CharField(max_length=250)),
                ('job_savelater', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
            ],
        ),
        migrations.AlterField(
            model_name='employer_candidate_jobanswer',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job'),
        ),
        migrations.AlterField(
            model_name='employer_expired_jobs',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job'),
        ),
        migrations.AlterField(
            model_name='employer_job_responses',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job'),
        ),
        migrations.AlterField(
            model_name='employer_jobquestions',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job'),
        ),
        migrations.DeleteModel(
            name='Employer_jobs',
        ),
    ]
