# Generated by Django 3.2.4 on 2021-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_employer_jobquestion_answer_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_job',
            name='job_salary',
            field=models.CharField(blank=True, max_length=1250),
        ),
        migrations.AddField(
            model_name='employer_profile',
            name='about_company',
            field=models.CharField(blank=True, max_length=2250),
        ),
    ]
