# Generated by Django 3.2.4 on 2021-06-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_auto_20210620_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_expired_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.DeleteModel(
            name='Employer_expired_jobs',
        ),
    ]
