# Generated by Django 3.2.4 on 2021-06-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_auto_20210621_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_job',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer_job',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer_job',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
