# Generated by Django 3.2.4 on 2021-06-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_auto_20210621_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_jobquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1250)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
        migrations.AlterField(
            model_name='employer_candidate_jobanswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_jobquestion'),
        ),
        migrations.DeleteModel(
            name='Employer_jobquestions',
        ),
    ]
