# Generated by Django 3.2.4 on 2021-06-27 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_employer_job_applied_employer_job_like_employer_job_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_candidate_jobanswer',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='employer_job',
            name='is_applied',
        ),
        migrations.RemoveField(
            model_name='employer_job',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='employer_job',
            name='is_saved',
        ),
        migrations.AlterField(
            model_name='employer_job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Part time', 'Part time'), ('Full time', 'Full time'), ('Internship', 'Internship')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employer_job',
            name='job_experience',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employer_job',
            name='job_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employer_job',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employer_jobquestion',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employer_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter valid phone number. Correct format is 91XXXXXXXX', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='Employer_job_responses',
        ),
    ]
