# Generated by Django 3.2.4 on 2021-07-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_auto_20210627_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_job_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.employer_job')),
            ],
        ),
    ]
