# Generated by Django 3.2.4 on 2021-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_employer_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_job',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Employer_job_skills',
        ),
    ]
