# Generated by Django 3.2.4 on 2021-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_remove_employer_job_job_savelater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer_jobquestion',
            name='employer_id',
        ),
    ]
