# Generated by Django 3.2.4 on 2021-07-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_remove_employer_candidate_jobanswer_employer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_job',
            name='is_save_later',
            field=models.BooleanField(default=False),
        ),
    ]
