# Generated by Django 3.2.4 on 2021-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_employer_job_is_save_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_job_applied',
            name='is_disqualified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer_job_applied',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
