# Generated by Django 3.2.4 on 2021-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0016_auto_20210711_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_job_applied',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
