# Generated by Django 3.2.4 on 2021-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='user_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
