# Generated by Django 3.2.4 on 2021-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_custom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_custom',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
