# Generated by Django 3.2.4 on 2021-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0002_auto_20210627_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
