# Generated by Django 3.2.4 on 2021-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_alter_user_custom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_custom',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
