# Generated by Django 3.2.4 on 2021-11-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_alter_user_custom_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_custom',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
