# Generated by Django 3.2.4 on 2021-07-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0002_auto_20210714_2340'),
        ('user_custom', '0004_user_custom_first_login'),
    ]

    operations = [
    ]
