# Generated by Django 3.2.4 on 2021-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0005_merge_20210725_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
