# Generated by Django 3.2.4 on 2021-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0007_auto_20210729_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
